export { default as dir_img } from "../assets/ceo.avif";
export { default as counsel } from "../assets/counsel.avif";
export { default as child_counsel } from "../assets/child.avif";
export { default as doc_img } from "../assets/doctor.avif";
export { default as pna } from "../assets/pna.svg";
export { default as converse } from "../assets/converse.avif";
export { default as convert } from "../assets/convert.avif";
export { default as work } from "../assets/work.svg";
export {default as suicide} from "../assets/suicide.avif";
export {default as art} from "../assets/art.avif";
export {default as eap} from "../assets/eap.svg";
export {default as bm} from "../assets/bm.svg";